language: python
cache:
  - "pip"
  - "yarn"
python:
  - "3.6"
install:
  - "nvm install --lts"
  - "nvm use --lts"
  - "pip install coveralls"
  - "pip install -r requirements.txt"
script:
  - "prospector"
  - "npm run build"
  - "npm test"
after_success:
  - "coveralls"
