language: python
cache:
  - "pip"
  - "yarn"
python:
  - "3.8"
install:
  # Purge virtualenv
  - "pip freeze | xargs pip uninstall -y"
  # Python Dependencies
  - "pip install pipenv"
  # Production Dependencies
  - "pipenv install"
  # Package Safety Check
  - "pipenv check"
  # Development Dependencies
  - "pipenv install --dev"
  # Node Dependencies
  - "nvm install --lts"
  - "nvm use --lts"
  - "pipenv run yarn install"
script:
  # Static Code Analysis
  - "pipenv run prospector"
  # Build Static Content
  - "pipenv run yarn build"
  - "pipenv run yarn bundle"
  # Django Tests
  - "pipenv run yarn test"
after_success:
  # Submit Coverage
  - "pipenv run coveralls"
deploy:
  skip_cleanup: true
  provider: script
  script: "bash deploy.sh"
  on:
    branch: master
