language: python
cache:
  - "pip"
  - "yarn"
python:
  - "3.6"
install:
  - "pip install pipenv"
  - "nvm install --lts"
  - "nvm use --lts"
  - "pipenv install --dev"
  - "pipenv run yarn install"
script:
  # Package Safety Check
  - "pipenv check"
  # Static Code Analysis
  - "pipenv run prospector"
  # Build Static Content
  - "pipenv run yarn build"
  # Django Tests
  - "pipenv run yarn test"
after_success:
  # Submit Coverage
  - "pipenv run coveralls"
