version: '3'

services:
  db:
    image: postgres
    networks:
      - web

  migration:
    build: .
    environment:
      - ENV=docker
    entrypoint: sh /code/reverie/migrate.sh
    volumes:
      - ./reverie/settings:/code/reverie/settings
      - ./campaign/migrations:/code/reverie/campaign/migrations
    depends_on:
      - db
    networks:
      - web

  reverie:
    build: .
    entrypoint: "pipenv run python manage.py runserver 0.0.0.0:8000 --settings reverie.settings.docker"
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
      - migration
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:reverie.docker.localhost"

  proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - web

networks:
  web:
    driver: bridge
